import { memo, useState, useRef } from 'react'
import { api } from '../api/client.js'

const PRIORITY_COLORS = {
  high: '#7F77DD',
  normal: 'transparent',
  low: '#B4B2A9',
}

const WEEKDAYS = ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa']

const TaskRow = memo(function TaskRow({ task, onToggle }) {
  const [optimistic, setOptimistic] = useState(null) // 'completed' | 'uncompleted' | 'skipped' | null
  const pendingRef = useRef(false)

  const completed = optimistic === 'completed' ? true
    : optimistic === 'uncompleted' ? false
    : task.completed
  const skipped = optimistic === 'skipped'

  const isOverdueVisible = task.isOverdue && !completed
  const borderColor = isOverdueVisible ? '#EF4444' : (PRIORITY_COLORS[task.priority] || 'transparent')
  const hasBorder = isOverdueVisible || task.priority !== 'normal'

  // Touch devices often fire a delayed synthetic 'click' ~300ms after
  // 'touchend' (double-tap-zoom detection). If that arrives after our
  // request already finished and released the lock, it reads as a brand
  // new click and immediately re-toggles the task. Keep the lock held for
  // a short grace period after the request completes to absorb it.
  const RELEASE_DELAY_MS = 400

  function releaseAfterDelay() {
    setTimeout(() => { pendingRef.current = false }, RELEASE_DELAY_MS)
  }

  async function handleClick() {
    if (pendingRef.current) return
    pendingRef.current = true
    setOptimistic(task.completed ? 'uncompleted' : 'completed')
    try {
      await api.post(`/tasks/${task.id}/complete`, {})
      await onToggle()
    } finally {
      setOptimistic(null)
      releaseAfterDelay()
    }
  }

  async function handleSkip(e) {
    e.stopPropagation()
    if (pendingRef.current) return
    pendingRef.current = true
    setOptimistic('skipped')
    try {
      await api.post(`/tasks/${task.id}/skip`, {})
      await onToggle()
    } finally {
      setOptimistic(null)
      releaseAfterDelay()
    }
  }

  let rowBg = 'bg-white dark:bg-gray-800'
  if (task.isOverdue && !completed) rowBg = 'bg-red-50 dark:bg-red-900/20'
  else if (task.pinned) rowBg = 'bg-orange-50 dark:bg-orange-900/20'

  return (
    <div
      className={`flex items-center gap-3 px-3 py-3 border-b border-gray-100 dark:border-gray-700 last:border-b-0 ${rowBg} cursor-pointer select-none touch-manipulation`}
      style={{ borderLeft: hasBorder ? `3px solid ${borderColor}` : '3px solid transparent' }}
      onClick={handleClick}
      data-testid="task-row"
      data-task-title={task.title}
      data-completed={completed}
    >
      <div className={`w-5 h-5 rounded flex-shrink-0 border-2 flex items-center justify-center transition-colors ${
        completed ? 'bg-green-500 border-green-500' : task.isOverdue ? 'border-red-400' : 'border-gray-300 dark:border-gray-500'
      }`}>
        {completed && (
          <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
          </svg>
        )}
      </div>
      <span className={`flex-1 text-sm ${completed ? 'line-through text-gray-400 dark:text-gray-500' : 'text-gray-800 dark:text-gray-200'}`}>
        {task.title}
        {task.isOnce && task.dueDate && (
          <span className="ml-1.5 text-xs bg-orange-100 dark:bg-orange-900/30 text-orange-700 dark:text-orange-400 px-1.5 py-0.5 rounded">
            {task.dueDate.split('-').reverse().join('.')}
          </span>
        )}
      </span>
      <div className="flex items-center gap-2 flex-shrink-0">
        {task.fixedWeekday != null && (
          <span className="text-xs text-orange-600 dark:text-orange-400 font-medium">{WEEKDAYS[task.fixedWeekday]}</span>
        )}
        {task.fixedDayOfMonth != null && (
          <span className="text-xs text-orange-600 dark:text-orange-400 font-medium">{task.fixedDayOfMonth}.</span>
        )}
        {task.isAutoGenerated && (
          <span className="text-xs bg-gray-100 dark:bg-gray-700 text-gray-500 dark:text-gray-400 px-1.5 py-0.5 rounded">Abfall</span>
        )}
        {task.isOverdue && !completed && (
          <span className="text-xs text-red-600 dark:text-red-400">überfällig</span>
        )}
      </div>
      {task.type === 'daily' && !completed && !skipped && (
        <button
          onClick={handleSkip}
          title="Heute nicht nötig"
          className="flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-full text-gray-300 dark:text-gray-600 hover:text-gray-500 dark:hover:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors text-base leading-none touch-manipulation"
        >
          ✕
        </button>
      )}
    </div>
  )
})

export default TaskRow
