import { memo, useState } from 'react'
import { api } from '../api/client.js'

const PRIORITY_COLORS = {
  high: '#7F77DD',
  normal: 'transparent',
  low: '#B4B2A9',
}

const WEEKDAYS = ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa']

const TaskRow = memo(function TaskRow({ task, onToggle }) {
  const [loading, setLoading] = useState(false)

  const borderColor = PRIORITY_COLORS[task.priority] || 'transparent'
  const hasBorder = task.priority !== 'normal'

  async function handleClick() {
    setLoading(true)
    try {
      await api.post(`/tasks/${task.id}/complete`, {})
      onToggle()
    } catch {}
    setLoading(false)
  }

  let rowBg = 'bg-white'
  if (task.isOverdue && !task.completed) rowBg = 'bg-red-50'
  else if (task.pinned) rowBg = 'bg-orange-50'

  return (
    <div
      className={`flex items-center gap-3 px-3 py-3 border-b border-gray-100 last:border-b-0 ${rowBg} cursor-pointer select-none`}
      style={{ borderLeft: hasBorder ? `3px solid ${borderColor}` : '3px solid transparent' }}
      onClick={handleClick}
    >
      <div className={`w-5 h-5 rounded flex-shrink-0 border-2 flex items-center justify-center transition-colors ${
        task.completed ? 'bg-green-500 border-green-500' : task.isOverdue ? 'border-red-400' : 'border-gray-300'
      }`}>
        {task.completed && (
          <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
          </svg>
        )}
      </div>
      <span className={`flex-1 text-sm ${task.completed ? 'line-through text-gray-400' : 'text-gray-800'}`}>
        {task.title}
        {task.isOnce && task.dueDate && (
          <span className="ml-1.5 text-xs bg-orange-100 text-orange-700 px-1.5 py-0.5 rounded">
            {task.dueDate.split('-').reverse().join('.')}
          </span>
        )}
      </span>
      <div className="flex items-center gap-2 flex-shrink-0">
        {task.fixedWeekday != null && (
          <span className="text-xs text-orange-600 font-medium">{WEEKDAYS[task.fixedWeekday]}</span>
        )}
        {task.fixedDayOfMonth != null && (
          <span className="text-xs text-orange-600 font-medium">{task.fixedDayOfMonth}.</span>
        )}
        {task.isAutoGenerated && (
          <span className="text-xs bg-gray-100 text-gray-500 px-1.5 py-0.5 rounded">Abfall</span>
        )}
        {task.isOverdue && !task.completed && (
          <span className="text-xs text-red-600">überfällig</span>
        )}
      </div>
      {loading && <div className="w-4 h-4 border-2 border-orange-400 border-t-transparent rounded-full animate-spin flex-shrink-0" />}
    </div>
  )
})

export default TaskRow
