// Seed speziell für die PWA-Install-Screenshots (frontend/e2e-screenshots).
// Anders als der E2E-Seed (scripts/e2e-seed.js), der auf Testbarkeit optimiert
// ist ("E2E Test Task" …), erzeugt dieser Seed realistische, vorzeigbare
// Inhalte: zwei benannte Nutzer, alltägliche Aufgaben in allen Typen, ein paar
// erledigte für heute (füllt Statistik, Verlauf und Ruhmeshalle) sowie
// Trophäen. Läuft gegen eine Wegwerf-DB (DATABASE_URL), nie gegen Produktion.
import bcrypt from 'bcryptjs'
import prisma from '../src/lib/prisma.js'

function ymd(d) {
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

async function main() {
  const now = new Date()
  const today = ymd(now)
  const inTwoDays = ymd(new Date(now.getTime() + 2 * 86400000))

  // Trophäen werden NICHT direkt gesetzt — der Scheduler (updateTrophyCache)
  // berechnet sie beim Start aus der TaskLog-Historie neu und würde gesetzte
  // Werte überschreiben. Stattdessen seeden wir unten Erledigungen in
  // vergangenen Zeiträumen mit klarem Sieger.
  const anna = await prisma.user.create({
    data: {
      email: 'anna@example.com',
      passwordHash: await bcrypt.hash('Screenshot1234!', 4),
      name: 'Anna',
      role: 'admin', // für den Verwaltungs-Screenshot
      approved: true,
      hasSeenSwipeTip: true,
    },
  })
  const ben = await prisma.user.create({
    data: {
      email: 'ben@example.com',
      passwordHash: await bcrypt.hash('Screenshot1234!', 4),
      name: 'Ben',
      role: 'user',
      approved: true,
      hasSeenSwipeTip: true,
    },
  })

  // Aufgaben in allen Typen; sortOrder bestimmt die Reihenfolge im Block.
  const daily = await Promise.all([
    prisma.task.create({ data: { title: 'Blumen gießen', type: 'daily', priority: 'normal', sortOrder: 0 } }),
    prisma.task.create({ data: { title: 'Küche aufräumen', type: 'daily', priority: 'high', sortOrder: 1 } }),
    prisma.task.create({ data: { title: 'Kaffeemaschine reinigen', type: 'daily', priority: 'low', sortOrder: 2 } }),
  ])
  const weekly = await Promise.all([
    prisma.task.create({ data: { title: 'Wäsche waschen', type: 'weekly', priority: 'normal', sortOrder: 0 } }),
    prisma.task.create({ data: { title: 'Bad putzen', type: 'weekly', priority: 'normal', sortOrder: 1 } }),
    prisma.task.create({ data: { title: 'Müll rausbringen', type: 'weekly', priority: 'normal', sortOrder: 2 } }),
  ])
  await prisma.task.create({ data: { title: 'Fenster putzen', type: 'monthly', priority: 'normal', sortOrder: 0 } })
  // Abfallkalender-Termin (bevorstehend) — erscheint im Einmalig-Block.
  await prisma.task.create({
    data: { title: 'Papiertonne rausstellen', type: 'once', dueDate: inTwoDays, isAutoGenerated: true, isActive: true },
  })

  // Ein paar heutige Erledigungen: füllt Statistik (heute/Woche/Monat),
  // Verlauf und gibt der Ruhmeshalle Inhalt. Erzeugt jeweils TaskCompletion
  // + passenden TaskLog, so wie es die /complete-Route täte.
  async function complete(task, user, offsetMinutes) {
    const completion = await prisma.taskCompletion.create({
      data: {
        taskId: task.id,
        completedBy: user.id,
        forDate: today,
        completedAt: new Date(now.getTime() - offsetMinutes * 60000),
      },
    })
    await prisma.taskLog.create({
      data: {
        taskId: task.id,
        taskTitle: task.title,
        status: 'completed',
        completedBy: user.id,
        userName: user.name,
        forDate: today,
        completionId: completion.id,
        loggedAt: new Date(now.getTime() - offsetMinutes * 60000),
      },
    })
  }

  await complete(daily[0], anna, 90)   // Blumen gießen — Anna
  await complete(weekly[1], anna, 40)  // Bad putzen — Anna
  await complete(weekly[2], ben, 20)   // Müll rausbringen — Ben

  // Vergangene Erledigungen für die Ruhmeshalle: updateTrophyCache vergibt
  // Pokale an den Alleinsieger je abgeschlossenem Tag/Woche/Monat (loggedAt in
  // der Vergangenheit). Anna dominiert, Ben gewinnt einen Tag. Die heutigen
  // Erledigungen oben zählen dafür bewusst nicht (nur < heute).
  const pool = [...daily, ...weekly]
  let poolIdx = 0
  function atNoonDaysAgo(n) {
    const d = new Date(now.getTime() - n * 86400000)
    d.setHours(12, 0, 0, 0)
    return d
  }
  async function pastLogs(user, daysAgoN, count) {
    const when = atNoonDaysAgo(daysAgoN)
    for (let i = 0; i < count; i++) {
      const task = pool[poolIdx++ % pool.length]
      await prisma.taskLog.create({
        data: {
          taskId: task.id, taskTitle: task.title, status: 'completed',
          completedBy: user.id, userName: user.name,
          forDate: ymd(when), loggedAt: when,
        },
      })
    }
  }
  await pastLogs(anna, 2, 3);  await pastLogs(ben, 2, 1)   // vorgestern → Tag: Anna
  await pastLogs(ben, 5, 2);   await pastLogs(anna, 5, 1)  // → Tag: Ben
  await pastLogs(anna, 10, 3); await pastLogs(ben, 10, 1)  // letzte Woche → Anna
  await pastLogs(anna, 40, 4); await pastLogs(ben, 40, 1)  // letzter Monat → Anna

  console.log('screenshot-seed: 2 Nutzer + Aufgaben + Erledigungen erstellt')
}

main()
  .catch(err => { console.error(err); process.exit(1) })
  .finally(() => prisma.$disconnect())
