import { describe, it, expect, vi, afterEach } from 'vitest'
import prisma from '../../src/lib/prisma.js'
import { cleanupOldWasteTasks } from '../../src/services/scheduler.js'

afterEach(() => vi.useRealTimers())

function mockToday(isoString) {
  vi.useFakeTimers()
  vi.setSystemTime(new Date(isoString))
}

async function createTask(overrides = {}) {
  return prisma.task.create({
    data: { title: 'Papiertonne rausstellen', type: 'once', priority: 'normal', ...overrides },
  })
}

describe('cleanupOldWasteTasks', () => {
  it('löscht inaktive Abfallkalender-Aufgaben, die älter als 7 Tage sind', async () => {
    mockToday('2026-07-10T10:00:00Z')
    const old = await createTask({ isAutoGenerated: true, isActive: false, dueDate: '2026-07-02' }) // 8 Tage her

    await cleanupOldWasteTasks()

    const found = await prisma.task.findUnique({ where: { id: old.id } })
    expect(found).toBeNull()
  })

  it('lässt inaktive Abfallkalender-Aufgaben unangetastet, die noch keine 7 Tage alt sind', async () => {
    mockToday('2026-07-10T10:00:00Z')
    const recent = await createTask({ isAutoGenerated: true, isActive: false, dueDate: '2026-07-05' }) // 5 Tage her

    await cleanupOldWasteTasks()

    const found = await prisma.task.findUnique({ where: { id: recent.id } })
    expect(found).toBeTruthy()
  })

  it('lässt aktive Abfallkalender-Aufgaben unangetastet, unabhängig vom Alter', async () => {
    mockToday('2026-07-10T10:00:00Z')
    const active = await createTask({ isAutoGenerated: true, isActive: true, dueDate: '2026-06-01' })

    await cleanupOldWasteTasks()

    const found = await prisma.task.findUnique({ where: { id: active.id } })
    expect(found).toBeTruthy()
  })

  it('lässt manuell erstellte (nicht auto-generierte) Aufgaben unangetastet', async () => {
    mockToday('2026-07-10T10:00:00Z')
    const manual = await createTask({ isAutoGenerated: false, isActive: false, dueDate: '2026-06-01' })

    await cleanupOldWasteTasks()

    const found = await prisma.task.findUnique({ where: { id: manual.id } })
    expect(found).toBeTruthy()
  })
})
