import { describe, it, expect, vi, afterEach, beforeEach } from 'vitest'
import prisma from '../../src/lib/prisma.js'

vi.mock('node-ical', () => ({
  default: { async: { fromURL: vi.fn() } },
}))
vi.mock('../../src/services/push.js', () => ({
  sendPushToUser: vi.fn(),
}))

const ical = (await import('node-ical')).default
const { sendPushToUser } = await import('../../src/services/push.js')
const { syncWasteCalendar, getWasteSyncStatus } = await import('../../src/services/waste-calendar.js')

const ORIGINAL_URL = process.env.WASTE_ICAL_URL

function vevent(summary, startISO) {
  return { type: 'VEVENT', summary, start: new Date(startISO) }
}

async function createAdmin(overrides = {}) {
  return prisma.user.create({
    data: { email: `${Math.random().toString(36).slice(2)}@test.com`, passwordHash: 'x', name: 'Admin', role: 'admin', approved: true, ...overrides },
  })
}

beforeEach(() => {
  process.env.WASTE_ICAL_URL = 'https://example.com/waste.ics'
})

afterEach(() => {
  vi.useRealTimers()
  process.env.WASTE_ICAL_URL = ORIGINAL_URL
  vi.mocked(ical.async.fromURL).mockReset()
  vi.mocked(sendPushToUser).mockReset()
})

describe('syncWasteCalendar', () => {
  it('erstellt nur den nächsten Termin pro Tonnentyp, nicht alle zukünftigen', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z')) // dueDate für 06.07 wäre heute

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Gelbe Tonne', '2026-07-06T00:00:00Z'), // dueDate 05.07 -> heute fällig
      e2: vevent('Gelbe Tonne', '2026-07-20T00:00:00Z'), // weit in der Zukunft
      e3: vevent('Gelbe Tonne', '2026-08-03T00:00:00Z'), // noch weiter weg
    })

    await syncWasteCalendar()

    const tasks = await prisma.task.findMany({ where: { isAutoGenerated: true, title: 'Gelbe Tonne rausstellen' } })
    expect(tasks).toHaveLength(1)
    expect(tasks[0].dueDate).toBe('2026-07-05')
  })

  it('legt eine Aufgabe nicht mehr als ~1 Woche im Voraus an', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Papiertonne', '2026-07-27T00:00:00Z'), // dueDate 26.07, >7 Tage weg
    })

    await syncWasteCalendar()

    const tasks = await prisma.task.findMany({ where: { isAutoGenerated: true, title: 'Papiertonne rausstellen' } })
    expect(tasks).toHaveLength(0)
  })

  it('bankt einen Termin innerhalb der ~1-Woche-Vorlauffrist vorab (nicht erst am Fälligkeitstag)', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))

    // Abholung 09.07 -> dueDate 08.07, 3 Tage entfernt (<= 7-Tage-Banking-Fenster)
    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Papiertonne', '2026-07-09T00:00:00Z'),
    })

    await syncWasteCalendar()

    const tasks = await prisma.task.findMany({ where: { isAutoGenerated: true, title: 'Papiertonne rausstellen' } })
    expect(tasks).toHaveLength(1)
    expect(tasks[0].dueDate).toBe('2026-07-08')
    expect(tasks[0].isActive).toBe(true)
  })

  it('entfernt eine verfrüht angelegte, unerledigte Aufgabe wieder, solange ihr Termin noch nicht ansteht', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))

    // Simuliert eine Aufgabe, die vor diesem Fix fälschlich zu früh angelegt wurde.
    await prisma.task.create({
      data: { title: 'Papiertonne rausstellen', type: 'once', dueDate: '2026-07-26', isAutoGenerated: true, isActive: true },
    })

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Papiertonne', '2026-07-27T00:00:00Z'),
    })

    await syncWasteCalendar()

    const tasks = await prisma.task.findMany({ where: { isAutoGenerated: true, title: 'Papiertonne rausstellen' } })
    expect(tasks).toHaveLength(0)
  })

  it('lässt eine verfrüht angelegte Aufgabe unangetastet, wenn sie bereits erledigt wurde', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))

    const task = await prisma.task.create({
      data: { title: 'Papiertonne rausstellen', type: 'once', dueDate: '2026-07-26', isAutoGenerated: true, isActive: true },
    })
    await prisma.taskCompletion.create({ data: { taskId: task.id, forDate: '2026-07-26' } })

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Papiertonne', '2026-07-27T00:00:00Z'),
    })

    await syncWasteCalendar()

    const stillThere = await prisma.task.findUnique({ where: { id: task.id } })
    expect(stillThere).toBeTruthy()
  })
})

describe('syncWasteCalendar — unerkannte Kalendereinträge', () => {
  it('trackt einen unbekannten Eintrag und meldet ihn per Push an alle Admins', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))
    const admin = await createAdmin()
    await prisma.user.create({ data: { email: 'user@test.com', passwordHash: 'x', name: 'User', role: 'user', approved: true } })

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Sperrmüll', '2026-07-10T00:00:00Z'), // erkennt keiner der WASTE_TYPES
    })

    await syncWasteCalendar()

    const status = await getWasteSyncStatus()
    expect(status.unmatchedSummaries).toEqual(['Sperrmüll'])
    expect(sendPushToUser).toHaveBeenCalledTimes(1)
    expect(sendPushToUser).toHaveBeenCalledWith(admin.id, expect.objectContaining({ body: expect.stringContaining('Sperrmüll') }))
  })

  it('meldet denselben unbekannten Eintrag nicht ein zweites Mal (kein Spam bei wiederholtem Sync)', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))
    await createAdmin()

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Sperrmüll', '2026-07-10T00:00:00Z'),
    })

    await syncWasteCalendar()
    await syncWasteCalendar()

    expect(sendPushToUser).toHaveBeenCalledTimes(1) // nur beim ersten Mal
    const status = await getWasteSyncStatus()
    expect(status.unmatchedSummaries).toEqual(['Sperrmüll']) // Anzeige bleibt trotzdem aktuell
  })

  it('ignoriert bereits vergangene unerkannte Einträge', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))
    await createAdmin()

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Sperrmüll', '2026-07-01T00:00:00Z'), // liegt in der Vergangenheit
    })

    await syncWasteCalendar()

    expect(sendPushToUser).not.toHaveBeenCalled()
    const status = await getWasteSyncStatus()
    expect(status.unmatchedSummaries).toEqual([])
  })

  it('liefert eine leere Liste, wenn alle Einträge erkannt wurden', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Gelbe Tonne', '2026-07-06T00:00:00Z'),
    })

    await syncWasteCalendar()

    const status = await getWasteSyncStatus()
    expect(status.unmatchedSummaries).toEqual([])
    expect(sendPushToUser).not.toHaveBeenCalled()
  })

  it('meldet einen zuvor gemeldeten, dann verschwundenen und erneut auftauchenden Eintrag nicht erneut (bleibt in notifiedSummaries)', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))
    await createAdmin()

    ical.async.fromURL.mockResolvedValue({ e1: vevent('Sperrmüll', '2026-07-10T00:00:00Z') })
    await syncWasteCalendar() // meldet einmalig

    ical.async.fromURL.mockResolvedValue({}) // Eintrag verschwindet aus dem Feed
    await syncWasteCalendar()
    const statusGone = await getWasteSyncStatus()
    expect(statusGone.unmatchedSummaries).toEqual([]) // Anzeige leert sich

    ical.async.fromURL.mockResolvedValue({ e1: vevent('Sperrmüll', '2026-07-12T00:00:00Z') })
    await syncWasteCalendar() // taucht wieder auf

    expect(sendPushToUser).toHaveBeenCalledTimes(1) // weiterhin nur der eine Push vom ersten Mal
  })
})
