import { describe, it, expect, vi, afterEach, beforeEach } from 'vitest'
import prisma from '../../src/lib/prisma.js'

vi.mock('node-ical', () => ({
  default: { async: { fromURL: vi.fn() } },
}))

const ical = (await import('node-ical')).default
const { syncWasteCalendar } = await import('../../src/services/waste-calendar.js')

const ORIGINAL_URL = process.env.WASTE_ICAL_URL

function vevent(summary, startISO) {
  return { type: 'VEVENT', summary, start: new Date(startISO) }
}

beforeEach(() => {
  process.env.WASTE_ICAL_URL = 'https://example.com/waste.ics'
})

afterEach(() => {
  vi.useRealTimers()
  process.env.WASTE_ICAL_URL = ORIGINAL_URL
  vi.mocked(ical.async.fromURL).mockReset()
})

describe('syncWasteCalendar', () => {
  it('erstellt nur den nächsten Termin pro Tonnentyp, nicht alle zukünftigen', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z')) // dueDate für 06.07 wäre heute

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Gelbe Tonne', '2026-07-06T00:00:00Z'), // dueDate 05.07 -> heute fällig
      e2: vevent('Gelbe Tonne', '2026-07-20T00:00:00Z'), // weit in der Zukunft
      e3: vevent('Gelbe Tonne', '2026-08-03T00:00:00Z'), // noch weiter weg
    })

    await syncWasteCalendar()

    const tasks = await prisma.task.findMany({ where: { isAutoGenerated: true, title: 'Gelbe Tonne rausstellen' } })
    expect(tasks).toHaveLength(1)
    expect(tasks[0].dueDate).toBe('2026-07-05')
  })

  it('legt eine Aufgabe erst am Tag vor dem Termin an, nicht schon Wochen vorher', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Papiertonne', '2026-07-27T00:00:00Z'), // dueDate 26.07, noch weit weg
    })

    await syncWasteCalendar()

    const tasks = await prisma.task.findMany({ where: { isAutoGenerated: true, title: 'Papiertonne rausstellen' } })
    expect(tasks).toHaveLength(0)
  })

  it('entfernt eine verfrüht angelegte, unerledigte Aufgabe wieder, solange ihr Termin noch nicht ansteht', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))

    // Simuliert eine Aufgabe, die vor diesem Fix fälschlich zu früh angelegt wurde.
    await prisma.task.create({
      data: { title: 'Papiertonne rausstellen', type: 'once', dueDate: '2026-07-26', isAutoGenerated: true, isActive: true },
    })

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Papiertonne', '2026-07-27T00:00:00Z'),
    })

    await syncWasteCalendar()

    const tasks = await prisma.task.findMany({ where: { isAutoGenerated: true, title: 'Papiertonne rausstellen' } })
    expect(tasks).toHaveLength(0)
  })

  it('lässt eine verfrüht angelegte Aufgabe unangetastet, wenn sie bereits erledigt wurde', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-05T10:00:00Z'))

    const task = await prisma.task.create({
      data: { title: 'Papiertonne rausstellen', type: 'once', dueDate: '2026-07-26', isAutoGenerated: true, isActive: true },
    })
    await prisma.taskCompletion.create({ data: { taskId: task.id, forDate: '2026-07-26' } })

    ical.async.fromURL.mockResolvedValue({
      e1: vevent('Papiertonne', '2026-07-27T00:00:00Z'),
    })

    await syncWasteCalendar()

    const stillThere = await prisma.task.findUnique({ where: { id: task.id } })
    expect(stillThere).toBeTruthy()
  })
})
