import cron from 'node-cron'
import prisma from '../lib/prisma.js'
import { sendPushToUser } from './push.js'
import { syncWasteCalendar } from './waste-calendar.js'
import { todayString, twoDaysAgoString, currentWeekStart, currentMonthStart, dateToISO } from '../lib/dates.js'
import { calculateTrophies } from '../lib/trophies.js'

async function cleanupExpiredTokens() {
  const now = new Date()
  const [rt, prt] = await Promise.all([
    prisma.refreshToken.deleteMany({ where: { expiresAt: { lt: now } } }),
    prisma.passwordResetToken.deleteMany({ where: { expiresAt: { lt: now } } }),
  ])
  if (rt.count > 0 || prt.count > 0) {
    console.log(`[Cleanup] ${rt.count} abgelaufene RefreshTokens, ${prt.count} PasswordResetTokens gelöscht`)
  }
}

async function expireDailyTasks() {
  const twoDaysAgo = twoDaysAgoString()
  const twoDaysAgoDate = new Date()
  twoDaysAgoDate.setDate(twoDaysAgoDate.getDate() - 2)
  const twoDaysAgoWeekday = twoDaysAgoDate.getDay()

  const tasks = await prisma.task.findMany({ where: { type: 'daily', isActive: true } })
  const dueTasks = tasks.filter(task => {
    if (task.createdAt > twoDaysAgoDate) return false
    const weekdays = task.weekdays ? JSON.parse(task.weekdays) : null
    return !weekdays || weekdays.length === 0 || weekdays.includes(twoDaysAgoWeekday)
  })
  if (dueTasks.length === 0) return

  const taskIds = dueTasks.map(t => t.id)
  const [completions, existingLogs, skippedLogs] = await Promise.all([
    prisma.taskCompletion.findMany({ where: { taskId: { in: taskIds }, forDate: twoDaysAgo }, select: { taskId: true } }),
    prisma.taskLog.findMany({ where: { taskId: { in: taskIds }, forDate: twoDaysAgo, status: 'expired' }, select: { taskId: true } }),
    prisma.taskLog.findMany({ where: { taskId: { in: taskIds }, forDate: twoDaysAgo, status: 'skipped' }, select: { taskId: true } }),
  ])
  const completedIds = new Set(completions.map(c => c.taskId))
  const loggedIds = new Set(existingLogs.map(l => l.taskId))
  const skippedIds = new Set(skippedLogs.map(l => l.taskId))

  await Promise.all(
    dueTasks
      .filter(t => !completedIds.has(t.id) && !loggedIds.has(t.id) && !skippedIds.has(t.id))
      .map(t => prisma.taskLog.create({ data: { taskId: t.id, taskTitle: t.title, status: 'expired', forDate: twoDaysAgo } }))
  )
}

async function expireWeeklyTasks() {
  const now = new Date()
  if (now.getDay() !== 1) return

  const lastMonday = new Date(now)
  lastMonday.setDate(now.getDate() - 7)
  const weekStart = dateToISO(lastMonday)

  const tasks = await prisma.task.findMany({ where: { type: 'weekly', isActive: true } })
  if (tasks.length === 0) return

  const completions = await prisma.taskCompletion.findMany({
    where: { taskId: { in: tasks.map(t => t.id) }, forDate: { gte: weekStart } },
    select: { taskId: true },
  })
  const completedIds = new Set(completions.map(c => c.taskId))
  const expired = tasks.filter(t => !completedIds.has(t.id))
  if (expired.length > 0) {
    await prisma.taskLog.createMany({
      data: expired.map(t => ({ taskId: t.id, taskTitle: t.title, status: 'expired', forDate: weekStart })),
    })
  }
}

async function expireMonthlyTasks() {
  const now = new Date()
  if (now.getDate() !== 1) return

  const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1)
  const monthStr = dateToISO(lastMonth)

  const tasks = await prisma.task.findMany({ where: { type: 'monthly', isActive: true } })
  if (tasks.length === 0) return

  const completions = await prisma.taskCompletion.findMany({
    where: { taskId: { in: tasks.map(t => t.id) }, forDate: { gte: monthStr } },
    select: { taskId: true },
  })
  const completedIds = new Set(completions.map(c => c.taskId))
  const expired = tasks.filter(t => !completedIds.has(t.id))
  if (expired.length > 0) {
    await prisma.taskLog.createMany({
      data: expired.map(t => ({ taskId: t.id, taskTitle: t.title, status: 'expired', forDate: monthStr })),
    })
  }
}

async function expireOnce() {
  const today = todayString()
  const tasks = await prisma.task.findMany({ where: { type: 'once', isActive: true } })
  const tasksWithDue = tasks.filter(t => t.dueDate)
  if (tasksWithDue.length === 0) return

  const completions = await prisma.taskCompletion.findMany({
    where: { taskId: { in: tasksWithDue.map(t => t.id) } },
    select: { taskId: true, forDate: true },
  })
  const completedIds = new Set(completions.map(c => c.taskId))

  const toDeactivate = []
  const toLog = []

  for (const t of tasksWithDue) {
    const isPastOrToday = t.dueDate <= today
    if (!isPastOrToday) continue

    if (t.isAutoGenerated) {
      // Auto-generated (waste calendar): always deactivate and log as expired if not done
      toDeactivate.push(t.id)
      if (!completedIds.has(t.id)) {
        toLog.push({ taskId: t.id, taskTitle: t.title, status: 'expired', forDate: t.dueDate })
      }
    } else if (completedIds.has(t.id)) {
      // Regular once task: deactivate when completed (uncompleted stay visible as overdue)
      // Includes tasks due today so they disappear after completion at midnight
      toDeactivate.push(t.id)
    }
  }

  await Promise.all([
    ...toDeactivate.map(id => prisma.task.update({ where: { id }, data: { isActive: false } })),
    toLog.length > 0 ? prisma.taskLog.createMany({ data: toLog, skipDuplicates: true }) : null,
  ].filter(Boolean))
}

function berlinTime(now) {
  const fmt = new Intl.DateTimeFormat('en-US', {
    timeZone: 'Europe/Berlin',
    hour: 'numeric', minute: 'numeric', weekday: 'short', hour12: false,
  })
  const parts = Object.fromEntries(fmt.formatToParts(now).map(p => [p.type, p.value]))
  const days = { Sun: 0, Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6 }
  return { hour: Number(parts.hour), minute: Number(parts.minute), day: days[parts.weekday] }
}

async function sendDailyReminders() {
  const globalSettings = await prisma.notificationSettings.findFirst({ where: { userId: null } })
  const [hours, minutes] = (globalSettings?.dailyTime || '21:00').split(':')
  const now = new Date()
  const berlin = berlinTime(now)
  if (berlin.hour !== Number(hours) || berlin.minute !== Number(minutes)) return

  const today = todayString()
  if (globalSettings?.lastDailyNotifiedDate === today) return

  const todayWeekday = now.getDay()
  const [tasks, users] = await Promise.all([
    prisma.task.findMany({ where: { type: 'daily', isActive: true } }),
    prisma.user.findMany({ where: { approved: true, vacationMode: false } }),
  ])

  const dueTodayIds = tasks
    .filter(t => { const w = t.weekdays ? JSON.parse(t.weekdays) : null; return !w || !w.length || w.includes(todayWeekday) })
    .map(t => t.id)

  const completedIds = new Set(
    (await prisma.taskCompletion.findMany({
      where: { forDate: today, taskId: { in: dueTodayIds } },
      select: { taskId: true },
    })).map(c => c.taskId)
  )

  const openCount = dueTodayIds.filter(id => !completedIds.has(id)).length
  console.log(`[Push] Täglich: ${openCount} offene Aufgaben, ${users.length} Nutzer, Zeit: ${berlin.hour}:${String(berlin.minute).padStart(2,'0')}`)

  if (openCount > 0) {
    await Promise.all(users.map(user => sendPushToUser(user.id, {
      title: 'Haushalt',
      body: `Du hast heute noch ${openCount} Aufgabe${openCount === 1 ? '' : 'n'} nicht abgeschlossen.`,
    })))
  }

  if (globalSettings) {
    await prisma.notificationSettings.update({ where: { id: globalSettings.id }, data: { lastDailyNotifiedDate: today } })
  } else {
    await prisma.notificationSettings.create({ data: { lastDailyNotifiedDate: today } })
  }
}

async function sendWeeklyReminders() {
  const globalSettings = await prisma.notificationSettings.findFirst({ where: { userId: null } })
  const weeklyDay = globalSettings?.weeklyDay ?? 6
  const [hours, minutes] = (globalSettings?.weeklyTime || '09:00').split(':')
  const now = new Date()
  const berlin = berlinTime(now)
  if (berlin.day !== weeklyDay || berlin.hour !== Number(hours) || berlin.minute !== Number(minutes)) return

  const weekStart = currentWeekStart()
  if (globalSettings?.lastWeeklyNotifiedDate === weekStart) return

  const [tasks, users] = await Promise.all([
    prisma.task.findMany({ where: { type: 'weekly', isActive: true } }),
    prisma.user.findMany({ where: { approved: true, vacationMode: false } }),
  ])

  const completions = tasks.length === 0 ? [] : await prisma.taskCompletion.findMany({
    where: { taskId: { in: tasks.map(t => t.id) }, forDate: { gte: weekStart } },
    select: { taskId: true },
  })
  const completedIds = new Set(completions.map(c => c.taskId))
  const openCount = tasks.filter(t => !completedIds.has(t.id)).length

  if (openCount > 0) {
    await Promise.all(users.map(user => sendPushToUser(user.id, {
      title: 'Haushalt',
      body: `Du hast noch ${openCount} offene Aufgabe${openCount === 1 ? '' : 'n'} in dieser Woche.`,
    })))
  }

  if (globalSettings) {
    await prisma.notificationSettings.update({ where: { id: globalSettings.id }, data: { lastWeeklyNotifiedDate: weekStart } })
  } else {
    await prisma.notificationSettings.create({ data: { lastWeeklyNotifiedDate: weekStart } })
  }
}

async function updateTrophyCache() {
  const users = await prisma.user.findMany({ where: { approved: true } })
  const allLogs = await prisma.taskLog.findMany({
    where: {
      status: 'completed',
      completedBy: { not: null },
      OR: [{ taskId: null }, { task: { type: { not: 'once' } } }],
    },
    select: { completedBy: true, loggedAt: true },
  })

  const today = todayString()
  const curWeekStart = currentWeekStart()
  const curMonthStart = currentMonthStart()

  const { dayTrophies, weekTrophies, monthTrophies } = calculateTrophies(allLogs, users, { today, curWeekStart, curMonthStart })

  await Promise.all(users.map(user => prisma.user.update({
    where: { id: user.id },
    data: {
      dayTrophies: dayTrophies[user.id] || 0,
      weekTrophies: weekTrophies[user.id] || 0,
      monthTrophies: monthTrophies[user.id] || 0,
    },
  })))
}

export function startScheduler() {
  cron.schedule('* * * * *', async () => {
    try {
      await sendDailyReminders()
      await sendWeeklyReminders()
    } catch (err) {
      console.error('[Scheduler] Fehler in Minuten-Job:', err)
    }
  }, { timezone: 'Europe/Berlin' })

  cron.schedule('0 0 * * *', async () => {
    for (const [name, job] of [
      ['cleanupExpiredTokens', cleanupExpiredTokens],
      ['expireDailyTasks', expireDailyTasks],
      ['expireWeeklyTasks', expireWeeklyTasks],
      ['expireMonthlyTasks', expireMonthlyTasks],
      ['expireOnce', expireOnce],
      ['updateTrophyCache', updateTrophyCache],
      ['syncWasteCalendar', syncWasteCalendar],
    ]) {
      try {
        await job()
      } catch (err) {
        console.error(`[Scheduler] Fehler in ${name}:`, err.message)
      }
    }
  }, { timezone: 'Europe/Berlin' })

  syncWasteCalendar().catch(err => console.error('[Scheduler] Fehler bei initialem Kalender-Sync:', err))
  updateTrophyCache().catch(err => console.error('[Scheduler] Fehler bei initialem Trophy-Cache:', err))
}
