import { DndContext, closestCenter } from '@dnd-kit/core'
import { SortableContext, verticalListSortingStrategy } from '@dnd-kit/sortable'
import SortableTask from './SortableTask.jsx'
import TaskFormFields from './TaskFormFields.jsx'
import WeatherStatusCard from './WeatherStatusCard.jsx'
import GlobalPauseCard from './GlobalPauseCard.jsx'
import Card from '../ui/Card.jsx'
import Button from '../ui/Button.jsx'
import { TYPE_LABELS } from './constants.js'

// Aufgabenverwaltung: Neue-Aufgabe-Formular, Export/Import, sortierbare Listen
// je Typ und der (schreibgeschützte) Abfallkalender-Abschnitt. Präsentations-
// Component; State/Handler liegen in Admin.jsx.
export default function TasksTab({
  tasks, wasteTasks, sensors, onDragEnd,
  showForm, onToggleForm, onExport, onImport,
  onSubmit, form, setForm, onEdit, onDelete,
}) {
  return (
    <div className="space-y-4">
      <Button variant="primary" onClick={onToggleForm} className="w-full">
        {showForm ? 'Abbrechen' : '+ Neue Aufgabe'}
      </Button>

      {/* Während des Anlegens ausgeblendet, damit das Formular nicht durch
          davorstehende Karten aus dem sichtbaren Bereich rutscht. */}
      {!showForm && (
        <>
          <WeatherStatusCard />
          <GlobalPauseCard />
        </>
      )}

      {showForm && (
        <form onSubmit={onSubmit} className="bg-surface-container rounded-card border border-outline p-4 space-y-3">
          <TaskFormFields form={form} setForm={setForm} />
          <Button type="submit" variant="primary" className="w-full">Aufgabe erstellen</Button>
        </form>
      )}

      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}>
        {['daily', 'weekly', 'monthly', 'once'].map(type => {
          // Abfallkalender-Aufgaben werden nicht manuell verwaltet — sie
          // laufen ausschließlich über den Kalender-Sync (eigener
          // Abschnitt weiter unten), tauchen hier also nicht auf.
          const group = tasks.filter(t => t.type === type && !t.isAutoGenerated && (type !== 'once' || t.isActive))
          return (
            <Card key={type} className="overflow-hidden mb-3">
              <div className="px-4 py-2.5 bg-surface-container-high border-b border-outline">
                <span className="text-xs font-semibold text-ink-muted uppercase tracking-wide">{TYPE_LABELS[type]}</span>
              </div>
              <SortableContext items={group.map(t => t.id)} strategy={verticalListSortingStrategy}>
                {group.length === 0 && <p className="text-sm text-ink-faint p-4 text-center">Keine Aufgaben</p>}
                {group.map(task => (
                  <SortableTask key={task.id} task={task} onEdit={onEdit} onDelete={onDelete} />
                ))}
              </SortableContext>
            </Card>
          )
        })}
      </DndContext>

      <Card className="overflow-hidden mb-3">
        <div className="px-4 py-2.5 bg-surface-container-high border-b border-outline">
          <span className="text-xs font-semibold text-ink-muted uppercase tracking-wide">Abfallkalender</span>
        </div>
        {wasteTasks.length === 0 && <p className="text-sm text-ink-faint p-4 text-center">Keine Termine</p>}
        {wasteTasks.map(task => (
          <div key={task.id} className="flex items-center gap-3 px-4 py-3 border-b border-outline last:border-b-0">
            <div className="flex-1 min-w-0">
              <span className="text-sm font-medium text-ink truncate">{task.title}</span>
              <div className="text-xs text-ink-faint mt-0.5">
                {task.dueDate?.split('-').reverse().join('.')}
                {' · '}
                {task.isActive
                  ? <span className="text-primary">Bevorstehend</span>
                  : <span className="text-ink-faint">Abgelaufen</span>}
              </div>
            </div>
            {!task.isActive && (
              <button onClick={() => onDelete(task.id)} className="text-xs text-danger hover:underline shrink-0">Löschen</button>
            )}
          </div>
        ))}
        <p className="text-xs text-ink-faint p-3">
          Diese Termine werden automatisch über den Abfallkalender-Sync verwaltet. Abgelaufene Einträge können manuell gelöscht werden und werden nach 7 Tagen automatisch entfernt.
        </p>
      </Card>

      <Card className="overflow-hidden">
        <div className="px-4 py-2.5 bg-surface-container-high border-b border-outline">
          <span className="text-xs font-semibold text-ink-muted uppercase tracking-wide">Export / Import</span>
        </div>
        <div className="p-4 flex gap-2">
          <Button variant="secondary" onClick={onExport} className="flex-1">
            ↓ Exportieren
          </Button>
          <label className="flex-1 border border-outline-strong text-ink rounded-control py-2 text-sm font-medium text-center cursor-pointer hover:bg-surface-container-high transition-colors">
            ↑ Importieren
            <input type="file" accept=".json" className="hidden" onChange={onImport} />
          </label>
        </div>
      </Card>
    </div>
  )
}
