import { DndContext, closestCenter } from '@dnd-kit/core'
import { SortableContext, verticalListSortingStrategy } from '@dnd-kit/sortable'
import SortableTask from './SortableTask.jsx'
import TaskFormFields from './TaskFormFields.jsx'
import WeatherStatusCard from './WeatherStatusCard.jsx'
import GlobalPauseCard from './GlobalPauseCard.jsx'
import { TYPE_LABELS } from './constants.js'

// Admin-Tab "Aufgaben": Neue-Aufgabe-Formular, Export/Import, sortierbare Listen
// je Typ und der (schreibgeschützte) Abfallkalender-Abschnitt. Präsentations-
// Component; State/Handler liegen in Admin.jsx.
export default function TasksTab({
  tasks, wasteTasks, sensors, onDragEnd,
  showForm, onToggleForm, onExport, onImport,
  onSubmit, form, setForm, onEdit, onDelete,
}) {
  return (
    <div className="space-y-4">
      <button
        onClick={onToggleForm}
        className="w-full bg-orange-600 text-white rounded-xl py-2.5 text-sm font-medium"
      >
        {showForm ? 'Abbrechen' : '+ Neue Aufgabe'}
      </button>

      {/* Während des Anlegens ausgeblendet, damit das Formular nicht durch
          davorstehende Karten aus dem sichtbaren Bereich rutscht. */}
      {!showForm && (
        <>
          <WeatherStatusCard />
          <GlobalPauseCard />
        </>
      )}

      {showForm && (
        <form onSubmit={onSubmit} className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 p-4 space-y-3">
          <TaskFormFields form={form} setForm={setForm} />
          <button type="submit" className="w-full bg-orange-600 text-white rounded-xl py-2 text-sm font-medium">Aufgabe erstellen</button>
        </form>
      )}

      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}>
        {['daily', 'weekly', 'monthly', 'once'].map(type => {
          // Abfallkalender-Aufgaben werden nicht manuell verwaltet — sie
          // laufen ausschließlich über den Kalender-Sync (eigener
          // Abschnitt weiter unten), tauchen hier also nicht auf.
          const group = tasks.filter(t => t.type === type && !t.isAutoGenerated && (type !== 'once' || t.isActive))
          return (
            <div key={type} className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 overflow-hidden mb-3">
              <div className="px-4 py-2.5 bg-gray-50 dark:bg-gray-700/50 border-b border-gray-100 dark:border-gray-700">
                <span className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">{TYPE_LABELS[type]}</span>
              </div>
              <SortableContext items={group.map(t => t.id)} strategy={verticalListSortingStrategy}>
                {group.length === 0 && <p className="text-sm text-gray-400 dark:text-gray-500 p-4 text-center">Keine Aufgaben</p>}
                {group.map(task => (
                  <SortableTask key={task.id} task={task} onEdit={onEdit} onDelete={onDelete} />
                ))}
              </SortableContext>
            </div>
          )
        })}
      </DndContext>

      <div className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 overflow-hidden mb-3">
        <div className="px-4 py-2.5 bg-gray-50 dark:bg-gray-700/50 border-b border-gray-100 dark:border-gray-700">
          <span className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">Abfallkalender</span>
        </div>
        {wasteTasks.length === 0 && <p className="text-sm text-gray-400 dark:text-gray-500 p-4 text-center">Keine Termine</p>}
        {wasteTasks.map(task => (
          <div key={task.id} className="flex items-center gap-3 px-4 py-3 border-b border-gray-100 dark:border-gray-700 last:border-b-0">
            <div className="flex-1 min-w-0">
              <span className="text-sm font-medium text-gray-800 dark:text-gray-200 truncate">{task.title}</span>
              <div className="text-xs text-gray-400 dark:text-gray-500 mt-0.5">
                {task.dueDate?.split('-').reverse().join('.')}
                {' · '}
                {task.isActive
                  ? <span className="text-orange-600 dark:text-orange-400">Bevorstehend</span>
                  : <span className="text-gray-400">Abgelaufen</span>}
              </div>
            </div>
            {!task.isActive && (
              <button onClick={() => onDelete(task.id)} className="text-xs text-red-500 dark:text-red-400 hover:underline shrink-0">Löschen</button>
            )}
          </div>
        ))}
        <p className="text-xs text-gray-400 dark:text-gray-500 p-3">
          Diese Termine werden automatisch über den Abfallkalender-Sync verwaltet. Abgelaufene Einträge können manuell gelöscht werden und werden nach 7 Tagen automatisch entfernt.
        </p>
      </div>

      <div className="flex gap-2">
        <button
          onClick={onExport}
          className="flex-1 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 rounded-xl py-2 text-sm font-medium"
        >
          ↓ Exportieren
        </button>
        <label className="flex-1 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 rounded-xl py-2 text-sm font-medium text-center cursor-pointer">
          ↑ Importieren
          <input type="file" accept=".json" className="hidden" onChange={onImport} />
        </label>
      </div>
    </div>
  )
}
