-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Task" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "priority" TEXT NOT NULL DEFAULT 'normal',
    "weekdays" TEXT,
    "fixedWeekday" INTEGER,
    "fixedDayOfMonth" INTEGER,
    "dueDate" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "allowMultiple" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "new_Task" ("createdAt", "dueDate", "fixedDayOfMonth", "fixedWeekday", "id", "isActive", "isAutoGenerated", "priority", "sortOrder", "title", "type", "weekdays") SELECT "createdAt", "dueDate", "fixedDayOfMonth", "fixedWeekday", "id", "isActive", "isAutoGenerated", "priority", "sortOrder", "title", "type", "weekdays" FROM "Task";
DROP TABLE "Task";
ALTER TABLE "new_Task" RENAME TO "Task";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
