-- AlterTable
ALTER TABLE "User" ADD COLUMN "dayTrophies" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "weekTrophies" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "monthTrophies" INTEGER NOT NULL DEFAULT 0;
